# Generated by Django 5.0.7 on 2024-08-02 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PageVists",
            new_name="PageVisit",
        ),
    ]
